// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	workspaces "github.com/sreis/securelister/pkg/apis/workspaces"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Workspace)(nil), (*workspaces.Workspace)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Workspace_To_workspaces_Workspace(a.(*Workspace), b.(*workspaces.Workspace), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workspaces.Workspace)(nil), (*Workspace)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workspaces_Workspace_To_v1_Workspace(a.(*workspaces.Workspace), b.(*Workspace), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkspaceList)(nil), (*workspaces.WorkspaceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_WorkspaceList_To_workspaces_WorkspaceList(a.(*WorkspaceList), b.(*workspaces.WorkspaceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workspaces.WorkspaceList)(nil), (*WorkspaceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workspaces_WorkspaceList_To_v1_WorkspaceList(a.(*workspaces.WorkspaceList), b.(*WorkspaceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkspaceSpec)(nil), (*workspaces.WorkspaceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_WorkspaceSpec_To_workspaces_WorkspaceSpec(a.(*WorkspaceSpec), b.(*workspaces.WorkspaceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workspaces.WorkspaceSpec)(nil), (*WorkspaceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workspaces_WorkspaceSpec_To_v1_WorkspaceSpec(a.(*workspaces.WorkspaceSpec), b.(*WorkspaceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkspaceStatus)(nil), (*workspaces.WorkspaceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_WorkspaceStatus_To_workspaces_WorkspaceStatus(a.(*WorkspaceStatus), b.(*workspaces.WorkspaceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*workspaces.WorkspaceStatus)(nil), (*WorkspaceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_workspaces_WorkspaceStatus_To_v1_WorkspaceStatus(a.(*workspaces.WorkspaceStatus), b.(*WorkspaceStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Workspace_To_workspaces_Workspace(in *Workspace, out *workspaces.Workspace, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_WorkspaceSpec_To_workspaces_WorkspaceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_WorkspaceStatus_To_workspaces_WorkspaceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Workspace_To_workspaces_Workspace is an autogenerated conversion function.
func Convert_v1_Workspace_To_workspaces_Workspace(in *Workspace, out *workspaces.Workspace, s conversion.Scope) error {
	return autoConvert_v1_Workspace_To_workspaces_Workspace(in, out, s)
}

func autoConvert_workspaces_Workspace_To_v1_Workspace(in *workspaces.Workspace, out *Workspace, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_workspaces_WorkspaceSpec_To_v1_WorkspaceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_workspaces_WorkspaceStatus_To_v1_WorkspaceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_workspaces_Workspace_To_v1_Workspace is an autogenerated conversion function.
func Convert_workspaces_Workspace_To_v1_Workspace(in *workspaces.Workspace, out *Workspace, s conversion.Scope) error {
	return autoConvert_workspaces_Workspace_To_v1_Workspace(in, out, s)
}

func autoConvert_v1_WorkspaceList_To_workspaces_WorkspaceList(in *WorkspaceList, out *workspaces.WorkspaceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]workspaces.Workspace)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_WorkspaceList_To_workspaces_WorkspaceList is an autogenerated conversion function.
func Convert_v1_WorkspaceList_To_workspaces_WorkspaceList(in *WorkspaceList, out *workspaces.WorkspaceList, s conversion.Scope) error {
	return autoConvert_v1_WorkspaceList_To_workspaces_WorkspaceList(in, out, s)
}

func autoConvert_workspaces_WorkspaceList_To_v1_WorkspaceList(in *workspaces.WorkspaceList, out *WorkspaceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Workspace)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_workspaces_WorkspaceList_To_v1_WorkspaceList is an autogenerated conversion function.
func Convert_workspaces_WorkspaceList_To_v1_WorkspaceList(in *workspaces.WorkspaceList, out *WorkspaceList, s conversion.Scope) error {
	return autoConvert_workspaces_WorkspaceList_To_v1_WorkspaceList(in, out, s)
}

func autoConvert_v1_WorkspaceSpec_To_workspaces_WorkspaceSpec(in *WorkspaceSpec, out *workspaces.WorkspaceSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1_WorkspaceSpec_To_workspaces_WorkspaceSpec is an autogenerated conversion function.
func Convert_v1_WorkspaceSpec_To_workspaces_WorkspaceSpec(in *WorkspaceSpec, out *workspaces.WorkspaceSpec, s conversion.Scope) error {
	return autoConvert_v1_WorkspaceSpec_To_workspaces_WorkspaceSpec(in, out, s)
}

func autoConvert_workspaces_WorkspaceSpec_To_v1_WorkspaceSpec(in *workspaces.WorkspaceSpec, out *WorkspaceSpec, s conversion.Scope) error {
	return nil
}

// Convert_workspaces_WorkspaceSpec_To_v1_WorkspaceSpec is an autogenerated conversion function.
func Convert_workspaces_WorkspaceSpec_To_v1_WorkspaceSpec(in *workspaces.WorkspaceSpec, out *WorkspaceSpec, s conversion.Scope) error {
	return autoConvert_workspaces_WorkspaceSpec_To_v1_WorkspaceSpec(in, out, s)
}

func autoConvert_v1_WorkspaceStatus_To_workspaces_WorkspaceStatus(in *WorkspaceStatus, out *workspaces.WorkspaceStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_WorkspaceStatus_To_workspaces_WorkspaceStatus is an autogenerated conversion function.
func Convert_v1_WorkspaceStatus_To_workspaces_WorkspaceStatus(in *WorkspaceStatus, out *workspaces.WorkspaceStatus, s conversion.Scope) error {
	return autoConvert_v1_WorkspaceStatus_To_workspaces_WorkspaceStatus(in, out, s)
}

func autoConvert_workspaces_WorkspaceStatus_To_v1_WorkspaceStatus(in *workspaces.WorkspaceStatus, out *WorkspaceStatus, s conversion.Scope) error {
	return nil
}

// Convert_workspaces_WorkspaceStatus_To_v1_WorkspaceStatus is an autogenerated conversion function.
func Convert_workspaces_WorkspaceStatus_To_v1_WorkspaceStatus(in *workspaces.WorkspaceStatus, out *WorkspaceStatus, s conversion.Scope) error {
	return autoConvert_workspaces_WorkspaceStatus_To_v1_WorkspaceStatus(in, out, s)
}
