/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by apiregister-gen. DO NOT EDIT.

package apis

import (
	"github.com/sreis/securelister/pkg/apis/workspaces"
	_ "github.com/sreis/securelister/pkg/apis/workspaces/install" // Install the workspaces group
	workspacesv1 "github.com/sreis/securelister/pkg/apis/workspaces/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
)

var (
	localSchemeBuilder = runtime.SchemeBuilder{
		workspacesv1.AddToScheme,
	}
	AddToScheme = localSchemeBuilder.AddToScheme
)

// GetAllApiBuilders returns all known APIGroupBuilders
// so they can be registered with the apiserver
func GetAllApiBuilders() []*builders.APIGroupBuilder {
	return []*builders.APIGroupBuilder{
		GetWorkspacesAPIBuilder(),
	}
}

var workspacesApiGroup = builders.NewApiGroupBuilder(
	"workspaces.sreis.pt",
	"github.com/sreis/securelister/pkg/apis/workspaces").
	WithUnVersionedApi(workspaces.ApiVersion).
	WithVersionedApis(
		workspacesv1.ApiVersion,
	).
	WithRootScopedKinds()

func GetWorkspacesAPIBuilder() *builders.APIGroupBuilder {
	return workspacesApiGroup
}
